- name: Docker - Create deploy docker-compose  directory
  ansible.builtin.file:
    path: "/opt/deploy/{{ drupal_project_name }}"
    state: directory
    owner: docker
    group: docker
    force: no

- name: Docker - Create deploy docker-compose  directory
  ansible.builtin.file:
    path: "/opt/deploy/{{ drupal_project_name }}/src"
    state: directory
    owner: docker
    group: docker
    force: no

- name: Docker - Create deploy docker-compose  directory
  ansible.builtin.file:
    path: "/opt/deploy/{{ drupal_project_name }}/db"
    state: directory
    owner: docker
    group: docker
    force: no

- name: Docker - Create deploy Dockerfile  directory
  ansible.builtin.file:
    path: "/opt/deploy/{{ drupal_project_name }}/php-fpm"
    state: directory
    owner: docker
    group: docker
    force: no

- name: Docker - Create deploy Dockerfile for deploy
  ansible.builtin.template:
    src: Dockefile.j2
    path: "/opt/deploy/{{ drupal_project_name }}/php-fpm/Dockerfile"
    mode: 0644
    owner: docker
    group: docker

- name: Docker - Create deploy xdebug for deploy
  ansible.builtin.template:
    src: xdebug.ini.j2
    path: "/opt/deploy/{{ drupal_project_name }}/php-fpm/xdebug.ini"
    mode: 0644
    owner: docker
    group: docker

- name: Docker - Copy Nginx Server conf
  ansible.builtin.template:
    src: server.nginx.j2
    path: "/opt/deploy/{{ drupal_project_name }}/server.conf"
    mode: 0644
    owner: docker
    group: docker

- name: Docker - Copy Nginx Custom Website
  ansible.builtin.template:
    src: conf.nginx.j2
    path: "/opt/deploy/{{ drupal_project_name }}/site.conf"
    mode: 0644
    owner: docker
    group: docker

- name: Docker - Pull image mariadb
  ansible.builtin.docker_image:
    name: mariadb:{{ mariadb_version }}
    source: pull
    state: present
  when: drupal_type_database == 'mariadb'

- name: Docker - Pull image postgresql
  ansible.builtin.docker_image:
    name: postgres:{{ postgres_version }}
    source: pull
    state: present
  when: drupal_type_database == 'postgresql'

- name: Docker - Pull image Nginx
  docker_image:
    name: nginx
    source: pull
    state: present

- name: "Docker - Copy Docker-compose for Mariadb"
  ansible.builtin.template:
    src: docker-compose-mariadb.j2
    dest: /opt/deploy/{{ drupal_project_name }}/docker-compose.yml
    mode: 0440
    owner: docker
    group: docker
  when: drupal_type_database == 'mariadb'

- name: "Docker - Copy Docker-compose for Postgresql"
  ansible.builtin.template:
    src: docker-compose-postgresql.j2
    dest: /opt/deploy/{{ drupal_project_name }}/docker-compose.yml
    mode: 0440
    owner: docker
    group: docker
  when: drupal_type_database == 'postgresql'

- name: Docker - Deploy Docker Compose
  ansible.builtin.command: 
    cmd: sudo docker-compose up -d
    chdir: "/opt/deploy/{{ drupal_project_name }}"

