---

- name: O.S. Packages for Centos Linux, Rocky Linux or RHEL.
  ansible.builtin.package:
    name: "{{ drupal_os_requirements }}"
    state: present


- name: REPO BLOCK - Install epel
  when:
    - (ansible_os_family == "RedHat" and
      ansible_distribution_major_version in [ "7", "8", "9" ])
  block:
    - name: REPO {{ ansible_distribution }} {{ ansible_distribution_major_version }} - Install epel gpg key
      ansible.builtin.rpm_key:
        key: "{{ epel_gpg_key }}"
        state: present

    - name: REPO {{ ansible_distribution }} {{ ansible_distribution_major_version }} - Install epel-release
      ansible.builtin.package:
        name: "{{ epel_url }}"
        state: present
      notify:
        - Update package cache

    - name: REPO {{ ansible_distribution }} {{ ansible_distribution_major_version }} - UPDATE
      become: yes
      ansible.builtin.command: "sudo dnf -y update"

    - name: REPO {{ ansible_distribution }} {{ ansible_distribution_major_version }} - DNF Config Manages
      become: yes
      ansible.builtin.command: "sudo dnf config-manager --set-enabled crb"

    - name: REPO {{ ansible_distribution }} {{ ansible_distribution_major_version }} - DNF epel-release epel-next-release
      become: yes
      ansible.builtin.command: "sudo dnf install epel-release epel-next-release"

    - name: REPO {{ ansible_distribution }} {{ ansible_distribution_major_version }} - DNF Docker repository
      become: yes
      ansible.builtin.command: "sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"


- name: "O.S. {{ ansible_distribution }} {{ ansible_distribution_major_version }} - Setup docker user"
  become: yes
  ansible.builtin.user:
    name: docker
    groups: "docker"
    append: yes

- name: "O.S. {{ ansible_distribution }} {{ ansible_distribution_major_version }} - install Docker CE"
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

    update_cache: yes
    state: present

- name: "O.S. {{ ansible_distribution }} {{ ansible_distribution_major_version }} - Fix to init service by warning permisse"
  become: yes
  ansible.builtin.command: "sudo chmod +x /etc/rc.d/rc.local"

- name: O.S. "{{ ansible_distribution }} {{ ansible_distribution_major_version }} - Enable service Docker-ce, and not touch the state"
  ansible.builtin.service:
    name: docker-ce
    enabled: yes

